/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import medicam.Conexion;

/**
 *
 * @author Nadia
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op_reg_medico = new javax.swing.JPanel();
        img_reg_doc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        op_reg_paciente = new javax.swing.JPanel();
        reg_ingresos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        op_costos = new javax.swing.JPanel();
        costos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        op_egreso = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bit_egresos = new javax.swing.JLabel();
        op_ingreso = new javax.swing.JPanel();
        registro_ingreso = new javax.swing.JLabel();
        reg_pacientes = new javax.swing.JLabel();
        op_reportes = new javax.swing.JPanel();
        btn_reporte = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        op_pizarra = new javax.swing.JPanel();
        pizarra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(51, 153, 0));

        op_reg_medico.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_reg_medico.setForeground(new java.awt.Color(204, 255, 204));
        op_reg_medico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_reg_medicoMouseClicked(evt);
            }
        });

        img_reg_doc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nadia\\Documents\\NetBeansProjects\\MediCam\\build\\classes\\imagenes\\doctor.png")); // NOI18N
        img_reg_doc.setPreferredSize(new java.awt.Dimension(112, 112));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Registrar Medico");

        javax.swing.GroupLayout op_reg_medicoLayout = new javax.swing.GroupLayout(op_reg_medico);
        op_reg_medico.setLayout(op_reg_medicoLayout);
        op_reg_medicoLayout.setHorizontalGroup(
            op_reg_medicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_reg_medicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(op_reg_medicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_reg_medicoLayout.createSequentialGroup()
                        .addComponent(img_reg_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_reg_medicoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        op_reg_medicoLayout.setVerticalGroup(
            op_reg_medicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_reg_medicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_reg_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        op_reg_paciente.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_reg_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_reg_pacienteMouseClicked(evt);
            }
        });

        reg_ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paciente.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Registrar Paciente");

        javax.swing.GroupLayout op_reg_pacienteLayout = new javax.swing.GroupLayout(op_reg_paciente);
        op_reg_paciente.setLayout(op_reg_pacienteLayout);
        op_reg_pacienteLayout.setHorizontalGroup(
            op_reg_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_reg_pacienteLayout.createSequentialGroup()
                .addGroup(op_reg_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(op_reg_pacienteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(reg_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(op_reg_pacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        op_reg_pacienteLayout.setVerticalGroup(
            op_reg_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_reg_pacienteLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(reg_ingresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        op_costos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_costos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_costosMouseClicked(evt);
            }
        });

        costos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/costo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Costos");

        javax.swing.GroupLayout op_costosLayout = new javax.swing.GroupLayout(op_costos);
        op_costos.setLayout(op_costosLayout);
        op_costosLayout.setHorizontalGroup(
            op_costosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_costosLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(op_costosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_costosLayout.createSequentialGroup()
                        .addComponent(costos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_costosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38))))
        );
        op_costosLayout.setVerticalGroup(
            op_costosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_costosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(costos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        op_egreso.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_egreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_egresoMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Bitacora de Egresos");

        bit_egresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agenda.png"))); // NOI18N

        javax.swing.GroupLayout op_egresoLayout = new javax.swing.GroupLayout(op_egreso);
        op_egreso.setLayout(op_egresoLayout);
        op_egresoLayout.setHorizontalGroup(
            op_egresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_egresoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bit_egresos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_egresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap())
        );
        op_egresoLayout.setVerticalGroup(
            op_egresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_egresoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(bit_egresos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        op_ingreso.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_ingreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_ingresoMouseClicked(evt);
            }
        });

        registro_ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hospitalizacion.png"))); // NOI18N

        reg_pacientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reg_pacientes.setText("Registar Ingreso");

        javax.swing.GroupLayout op_ingresoLayout = new javax.swing.GroupLayout(op_ingreso);
        op_ingreso.setLayout(op_ingresoLayout);
        op_ingresoLayout.setHorizontalGroup(
            op_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_ingresoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registro_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(op_ingresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reg_pacientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        op_ingresoLayout.setVerticalGroup(
            op_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_ingresoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(registro_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_pacientes)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        op_reportes.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_reportesMouseClicked(evt);
            }
        });

        btn_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Reportes");

        javax.swing.GroupLayout op_reportesLayout = new javax.swing.GroupLayout(op_reportes);
        op_reportes.setLayout(op_reportesLayout);
        op_reportesLayout.setHorizontalGroup(
            op_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_reportesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31))
            .addGroup(op_reportesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        op_reportesLayout.setVerticalGroup(
            op_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_reportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        op_pizarra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), null));
        op_pizarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_pizarraMouseClicked(evt);
            }
        });

        pizarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mosaico.png"))); // NOI18N
        pizarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizarraMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pacientes Activos");

        javax.swing.GroupLayout op_pizarraLayout = new javax.swing.GroupLayout(op_pizarra);
        op_pizarra.setLayout(op_pizarraLayout);
        op_pizarraLayout.setHorizontalGroup(
            op_pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_pizarraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(op_pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_pizarraLayout.createSequentialGroup()
                        .addComponent(pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, op_pizarraLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );
        op_pizarraLayout.setVerticalGroup(
            op_pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(op_pizarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pizarra, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Bienvenido");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Seleccione una operacion");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(op_reg_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(op_reg_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(op_egreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op_pizarra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(op_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op_costos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(op_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(171, 171, 171))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(op_costos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(op_reg_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(op_reg_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(op_reportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(op_ingreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(op_egreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(op_pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op_reg_pacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_reg_pacienteMouseClicked
        medicam.Control_Operaciones.btn_reg_paciente();
    }//GEN-LAST:event_op_reg_pacienteMouseClicked

    private void op_reg_medicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_reg_medicoMouseClicked
        medicam.Control_Operaciones.btn_reg_medico();
    }//GEN-LAST:event_op_reg_medicoMouseClicked

    private void op_costosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_costosMouseClicked
        medicam.Control_Operaciones.btn_costos();
    }//GEN-LAST:event_op_costosMouseClicked

    private void pizarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizarraMouseClicked
        
    }//GEN-LAST:event_pizarraMouseClicked

    private void op_ingresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_ingresoMouseClicked
        medicam.Control_Operaciones.btn_reg_ingreso();
    }//GEN-LAST:event_op_ingresoMouseClicked

    private void op_egresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_egresoMouseClicked
        medicam.Control_Operaciones.btn_egresos();
    }//GEN-LAST:event_op_egresoMouseClicked

    private void op_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_reportesMouseClicked
        medicam.Control_Operaciones.btn_reportes();
    }//GEN-LAST:event_op_reportesMouseClicked

    private void op_pizarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_pizarraMouseClicked
        medicam.Control_Operaciones.btn_pizarra();
    }//GEN-LAST:event_op_pizarraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bit_egresos;
    private javax.swing.JLabel btn_reporte;
    private javax.swing.JLabel costos;
    private javax.swing.JLabel img_reg_doc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel op_costos;
    private javax.swing.JPanel op_egreso;
    private javax.swing.JPanel op_ingreso;
    private javax.swing.JPanel op_pizarra;
    private javax.swing.JPanel op_reg_medico;
    private javax.swing.JPanel op_reg_paciente;
    private javax.swing.JPanel op_reportes;
    private javax.swing.JLabel pizarra;
    private javax.swing.JLabel reg_ingresos;
    private javax.swing.JLabel reg_pacientes;
    private javax.swing.JLabel registro_ingreso;
    // End of variables declaration//GEN-END:variables
}
